  - name: Check if the FCOS template already exists
    shell: "govc find -type m | grep {{ vcenter.template_name }}" # noqa 301
    register: template_exists
    ignore_errors: yes

  - name: Delete FCOS template if skip_ova=false
    command: "govc vm.destroy {{ vcenter.template_name }}" # noqa 301
    when:
      - skip_ova is not defined
      - template_exists.rc == 0

  - name: Download the ova file
    get_url:
      url: "{{ download.fcos_ova }}"
      dest: "{{ playbook_dir }}/downloads/{{ vcenter.template_name }}.ova"
      validate_certs: no
    when: skip_ova is not defined

  - name: Deploy the OVA template into vCenter
    shell: "govc import.ova --name={{ vcenter.template_name }} --ds={{ vcenter.datastore }} --options={{ playbook_dir }}/files/options.json {{ playbook_dir }}/downloads/{{ vcenter.template_name }}.ova"  # noqa 301
    when: skip_ova is not defined
